ConfigFile = './config.toml'

[application]
DefaultPageSize = 300
DisableSidebar = false
SidebarOverlay = false
MaxQueryHistoryPerConnection = 100
theme = "dark"  # Available: dark, light, solarized, gruvbox, nord

[[database]]
Name = 'support'
DSN = 'postgres://postgres:postgres@localhost:5432/support?sslmode=disable'
Driver = 'postgres'
Username = 'postgres'
Password = 'postgres'
Hostname = 'localhost'
Port = '5432'
DBName = 'support'
DSNParams = ''
Commands = []
