ConfigFile = 'd:\Github\sqlcmder\config.toml'

[application]
DefaultPageSize = 300
DisableSidebar = false
SidebarOverlay = false
MaxQueryHistoryPerConnection = 100
theme = 'dark'

[[database]]
Name = 'press@mysql'
DSN = 'mysql://root:root@localhost:3306/press'
DsnCustom = 'mysql://root:root@localhost:3306/press'
DsnAuto = 'mysql://root:root@localhost:3306/press'
DsnValue = 'mysql://root:root@localhost:3306/press'
Driver = 'mysql'
Username = 'root'
Password = 'root'
Hostname = 'localhost'
Port = '3306'
DBName = 'press'
DSNParams = ''
Commands = []
